apiVersion: apps/v1
kind: Deployment
metadata:
  name: frp-operator
  labels:
    app.kubernetes.io/part-of: frp-operator
    app.kubernetes.io/name: frp-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: frp-operator
      app.kubernetes.io/name: frp-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: frp-operator
        app.kubernetes.io/name: frp-operator
    spec:
      serviceAccountName: frp-operator
      automountServiceAccountToken: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - name: frp-operator
          image: frp-operator
          imagePullPolicy: IfNotPresent
          command: ['/app/frp-operator']
          args: ['--server-addr', '192.168.100.1', '--server-port', '7000']
          env:
            - name: RUST_LOG
              value: frp_operator=debug
            - name: AUTH_TOKEN
              value: '12345678'
