apiVersion: apps/v1
kind: Deployment
metadata:
  name: frp-operator
  labels:
    app.kubernetes.io/part-of: frp-operator
    app.kubernetes.io/name: frp-operator
  namespace: frp-operator-system
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: frp-operator
      app.kubernetes.io/name: frp-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: frp-operator
        app.kubernetes.io/name: frp-operator
    spec:
      serviceAccountName: frp-operator
      automountServiceAccountToken: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - name: frp-operator
          image: frp-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: frp_operator=debug
