apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frp-operator-system
resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - ingressclass.yaml
